# -*- coding: utf-8 -*-

# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_infoDialog(object):
    def setupUi(self, infoDialog):
        infoDialog.setObjectName("infoDialog")
        infoDialog.resize(277, 141)
        infoDialog.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.buttonBox = QtWidgets.QDialogButtonBox(infoDialog)
        self.buttonBox.setGeometry(QtCore.QRect(10, 100, 251, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.dialogLabel = QtWidgets.QLabel(infoDialog)
        self.dialogLabel.setGeometry(QtCore.QRect(30, 20, 221, 71))
        self.dialogLabel.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.dialogLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.dialogLabel.setWordWrap(True)
        self.dialogLabel.setObjectName("dialogLabel")

        self.retranslateUi(infoDialog)
        self.buttonBox.accepted.connect(infoDialog.accept)  # type: ignore
        self.buttonBox.rejected.connect(infoDialog.reject)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(infoDialog)

    def retranslateUi(self, infoDialog):
        _translate = QtCore.QCoreApplication.translate
        infoDialog.setWindowTitle(_translate("infoDialog", "End of file"))
        self.dialogLabel.setText(
            _translate("infoDialog", "Reached end of file. Try searching from the start or change searching phrase."))
