# -*- coding: utf-8 -*-

# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1011, 544)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.openFileButton = QtWidgets.QPushButton(self.centralwidget)
        self.openFileButton.setGeometry(QtCore.QRect(20, 10, 141, 31))
        self.openFileButton.setObjectName("openFileButton")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(20, 110, 971, 361))
        self.textBrowser.setReadOnly(True)
        self.textBrowser.setObjectName("textBrowser")
        self.searchStartButton = QtWidgets.QPushButton(self.centralwidget)
        self.searchStartButton.setGeometry(QtCore.QRect(180, 10, 141, 31))
        self.searchStartButton.setObjectName("searchStartButton")
        self.searchInput = QtWidgets.QLineEdit(self.centralwidget)
        self.searchInput.setGeometry(QtCore.QRect(20, 60, 971, 31))
        self.searchInput.setObjectName("searchInput")
        self.loadMoreButton = QtWidgets.QPushButton(self.centralwidget)
        self.loadMoreButton.setGeometry(QtCore.QRect(20, 470, 971, 23))
        self.loadMoreButton.setObjectName("loadMoreButton")
        self.searchNextButton = QtWidgets.QPushButton(self.centralwidget)
        self.searchNextButton.setGeometry(QtCore.QRect(340, 10, 141, 31))
        self.searchNextButton.setObjectName("searchNextButton")
        self.radioButtonLemmatization = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButtonLemmatization.setGeometry(QtCore.QRect(690, 10, 91, 31))
        self.radioButtonLemmatization.setObjectName("radioButtonLemmatization")
        self.radioButtonStemming = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButtonStemming.setGeometry(QtCore.QRect(600, 10, 81, 31))
        self.radioButtonStemming.setObjectName("radioButtonStemming")
        self.radioButtonNone = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButtonNone.setGeometry(QtCore.QRect(530, 10, 61, 31))
        self.radioButtonNone.setChecked(True)
        self.radioButtonNone.setObjectName("radioButtonNone")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1011, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Text Search"))
        self.openFileButton.setText(_translate("MainWindow", "Open File"))
        self.searchStartButton.setText(_translate("MainWindow", "Search From Start"))
        self.searchInput.setPlaceholderText(_translate("MainWindow", "Search phrase"))
        self.loadMoreButton.setText(_translate("MainWindow", "Load more"))
        self.searchNextButton.setText(_translate("MainWindow", "Find Next"))
        self.radioButtonLemmatization.setText(_translate("MainWindow", "Lemmatization"))
        self.radioButtonStemming.setText(_translate("MainWindow", "Stemming"))
        self.radioButtonNone.setText(_translate("MainWindow", "None"))
